server:
  port: 8001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres

    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 30000
      maxLifetime: 60000
      leakDetectionThreshold: 180000
      connectionTimeout: 120000
      transaction-isolation: 2
      auto-commit: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true
  main:
    lazy-initialization: false

security:
  jwt:
    secret:
      4vzfsjym7t9lu

logging:
  level:
    org:
      springframework:
        security: info
        boot.autoconfigure: info
