package com.example.demo.exceptions;

public enum ErrorCode {

    ENTITY_NOT_FOUND,
    FIELD_VALUE_UNIQUE,
    REQUIRED_FIELD,
    VALUE_DID_NOT_MATCH,

    USERNAME_NOT_FOUND,

    VALIDATION_ERROR,
    UN_AUTHORIZED,
    HAS_NOT_PRODUCT_IN_WAREHOUSE,
    HAS_NOT_ENOUGH_PRODUCT_IN_WAREHOUSE;


}
